name: Update lists

on:
workflow_dispatch:
  - cron: '* 3 * * 5'

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Create release dir
        run: mkdir -p ../release-versions
      - name: Fetch release version
        run: |
          curl -sL https://github.com/StevenBlack/hosts/releases/latest | \
          jq -r ".tag_name" > ../release-versions/upstr_list_latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "new release"
          git push

